image: prefec2/jdk11-maven-363-gradle671

variables:
  GIT_CLEAN_FLAGS: none

cache:
  paths:

stages:
- compile
- check
- test
- package

compile:
  tags:
    - exec-docker
  stage: compile
  script:
    - ./gradlew --refresh-dependencies compileJava

check:
  tags:
    - exec-docker
  stage: check
  script:
    - ./gradlew -x test check
    - ./gradlew -x test checkstyleMain checkstyleTest pmdMain pmdTest

test:
  tags:
    - exec-docker
  stage: test
  script:
    - ./gradlew test

package:
  tags:
    - exec-docker
  stage: package
  script:
    - ./gradlew build
    - ./assemble-tools.sh
  artifacts:
    paths:
     - ./build/oceandsl-tools.tgz
