image: prefec2/jdk11-maven-363-gradle671

variables:
  GIT_CLEAN_FLAGS: none

cache:
  paths:

stages:
- compile
- check
- test
- package

compile:
  tags:
    - exec-docker
  stage: compile
  script:
    - ./gradlew compileJava

check:
  tags:
    - exec-docker
  stage: check
  script:
    - ./gradlew -x test check

test:
  tags:
    - exec-docker
  stage: test
  script:
    - ./gradlew test

package:
  tags:
    - exec-docker
  stage: package
  script:
    - ./gradlew build
  artifacts:
    paths:
     - ./tools/create-architecture-model/build/distributions/
